name: feems-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.3
  - pip
  - numpy=1.19.5
  - scipy=1.5.0
  - scikit-learn=0.23.1
  - matplotlib=3.2.2
  - pyproj=2.6.1.post1
  - networkx=2.4.0
  - shapely=1.7.1
  - fiona
  - pytest=5.4.3
  - pep8=1.7.1
  - flake8=3.8.3
  - click=7.1.2
  - setuptools=49.1.0
  - pandas-plink=2.2.9
  - msprime=1.0.0
  - suitesparse=5.7.2
  - scikit-sparse=0.4.4
  - cartopy=0.18.0
  - jupyter=1.0.0
  - jupyterlab=2.1.5
  - sphinx=3.1.2
  - sphinx_rtd_theme=0.5.0
  - nbsphinx=0.7.1
  - sphinx-autodoc-typehints
  - ipykernel
  - pip:
    - "--editable=git+https://github.com/NovembreLab/feems#egg=feems"